name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      # Install dependencies for backend
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      # Install dependencies for frontend
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      # Build Angular frontend
      - name: Build Angular App
        run: |
          cd frontend
          npm run build -- --configuration=production

  deploy:
    name: Deploy to AWS EC2 (Amazon Linux)
    runs-on: self-hosted # No ubuntu-latest since we use Amazon Linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Deploy to AWS EC2 via SSH
      - name: Deploy to AWS EC2
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USER: ${{ secrets.AWS_USER }}
        run: |
          echo "$AWS_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $AWS_USER@$AWS_HOST << 'EOF'
            sudo yum update -y
            sudo yum install -y git nodejs npm nginx

            # Clone the repository
            cd /home/ec2-user/
            if [ -d "my-app" ]; then
              cd my-app && git pull origin main
            else
              git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO.git my-app
              cd my-app
            fi

            # Install & Build Backend
            cd backend
            npm install
            pm2 restart server || pm2 start server.js --name "backend"

            # Install & Build Angular Frontend
            cd ../frontend
            npm install
            npm run build -- --configuration=production
            sudo cp -r dist/* /usr/share/nginx/html

            # Restart Services
            sudo systemctl restart nginx
          EOF
